export class DashboardActions {
  static WIDGET_GET_CONNECTION_STATUS: string = 'WIDGET_GET_CONNECTION_STATUS';
  static WIDGET_SET_CONNECTION_STATUS: string = 'WIDGET_SET_CONNECTION_STATUS';

  static WIDGET_GET_DEVICE_STATUS: string = 'WIDGET_GET_DEVICE_STATUS';
  static WIDGET_SET_DEVICE_STATUS: string = 'WIDGET_SET_DEVICE_STATUS';

  static WIDGET_GET_ONLINE_STATUS: string = 'WIDGET_GET_ONLINE_STATUS';
  static WIDGET_SET_ONLINE_STATUS: string = 'WIDGET_SET_ONLINE_STATUS';

  static WIDGET_GET_ACTIONS_STATUS: string = 'WIDGET_GET_ACTIONS_STATUS';
  static WIDGET_SET_ACTIONS_STATUS: string = 'WIDGET_SET_ACTIONS_STATUS';

  static WIDGET_GET_ISSUER_ACTIONS_STATUS: string = 'WIDGET_GET_ISSUER_ACTIONS_STATUS';
  static WIDGET_SET_ISSUER_ACTIONS_STATUS: string = 'WIDGET_SET_ISSUER_ACTIONS_STATUS';
}
