export const GeneralConstants = {
  Banks:{
    99:{ "bankNo":99 ,"bankName":"בנק ישראל"},
    12:{ "bankNo":12 ,"bankName":"בנק הפועלים"},
    10:{ "bankNo":10 ,"bankName":"בנק לאומי"},
    11:{ "bankNo":11 ,"bankName":"בנק דיסקונט"},
    20:{ "bankNo":20 ,"bankName":"בנק מזרחי טפחות"},
    31:{ "bankNo":31 ,"bankName":"הבנק הבינלאומי הראשון"},
    14:{ "bankNo":14 ,"bankName":"בנק אוצר החייל"},
    17:{ "bankNo":17 ,"bankName":"בנק מרכנתיל דיסקונט"},
    9: { "bankNo":9  ,"bankName":"בנק הדואר"},
    13:{ "bankNo":13 ,"bankName":"בנק איגוד"},
    46:{ "bankNo":46 ,"bankName":"בנק מסד"},
    52:{ "bankNo":52 ,"bankName":"בנק פועלי אגודת ישראל"},
    90:{ "bankNo":90 ,"bankName":"בנק דיסקונט למשכנתאות"},
    77:{ "bankNo":77 ,"bankName":"בנק לאומי למשכנתאות בע\"מ"},
    4: { "bankNo":4  ,"bankName":"בנק יהב לעובדי המדינה"},
    26:{ "bankNo":26 ,"bankName":"יובנק בע\"מ"},
    7: { "bankNo":7  ,"bankName":"בנק לפיתוח התעשיה"},
    8: { "bankNo":8  ,"bankName":"בנק הספנות לישראל"},
    6: { "bankNo":6  ,"bankName":"בנק אדנים"},
    54:{ "bankNo":54 ,"bankName":"בנק ירושלים"},
    34:{ "bankNo":34 ,"bankName":"בנק ערבי ישראלי"},
    1: { "bankNo":1  ,"bankName":"בנק יורו טרייד"},
    19:{ "bankNo":19 ,"bankName":"בנק החקלאות לישראל"},
    22:{ "bankNo":22 ,"bankName":"בנק סיטי"},
    48:{ "bankNo":48 ,"bankName":"קופת העובד הלאומי"},
    68:{ "bankNo":68 ,"bankName":"בנק אוצר השלטון המקומי"},
    23:{ "bankNo":23 ,"bankName":"HSBC"},
    67:{ "bankNo":67 ,"bankName":"Arab Land Bank"},
    25:{ "bankNo":25 ,"bankName":"BNP Paribas Israel"},
    39:{ "bankNo":39 ,"bankName":"SBI State Bank of India"}
  }
};
